apiVersion: v1
kind: Service
metadata:
  name: multi-agent-manufacturing-service
  labels:
    app: multi-agent-manufacturing-system
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: multi-agent-manufacturing-system
  ports:
    - name: streamlit
      protocol: TCP
      port: 80
      targetPort: 8501
      nodePort: 30001